version: '3'

vars:
  API_DIR: ./api
  WEB_DIR: ./web
  VERSION_PKG: github.com/jmylchreest/refyne-api/internal/version
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "0.0.0-dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  DIRTY:
    sh: git diff --quiet 2>/dev/null && echo "false" || echo "true"
  LDFLAGS: >-
    -X {{.VERSION_PKG}}.Version={{.VERSION}}
    -X {{.VERSION_PKG}}.Commit={{.COMMIT}}
    -X {{.VERSION_PKG}}.Date={{.DATE}}
    -X {{.VERSION_PKG}}.Dirty={{.DIRTY}}

tasks:
  # API tasks
  api:deps:
    desc: Download Go dependencies
    dir: '{{.API_DIR}}'
    cmds:
      - go mod tidy
      - go mod download

  api:build:
    desc: Build the API with version info
    dir: '{{.API_DIR}}'
    env:
      CGO_ENABLED: "1"
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o ../bin/refyne-api ./cmd/refyne-api

  api:build-prod:
    desc: Build optimized API binary for production
    dir: '{{.API_DIR}}'
    env:
      CGO_ENABLED: "0"
    cmds:
      - go build -trimpath -ldflags "-s -w {{.LDFLAGS}}" -o ../bin/refyne-api ./cmd/refyne-api

  api:dev:
    desc: Run API in development mode with hot reload
    dir: '{{.API_DIR}}'
    dotenv: ['.env', '.env.local']
    env:
      CGO_ENABLED: "1"
      LOG_FORMAT: text
      LOG_LEVEL: debug
      DATABASE_URL: file:../refyne-dev.db
      CORS_ORIGINS: http://localhost:3000
    cmds:
      - air

  api:run:
    desc: Run API without hot reload
    dir: '{{.API_DIR}}'
    dotenv: ['.env', '.env.local']
    env:
      CGO_ENABLED: "1"
      LOG_FORMAT: text
      LOG_LEVEL: debug
      DATABASE_URL: file:../refyne-dev.db
      CORS_ORIGINS: http://localhost:3000
    cmds:
      - go run -ldflags "{{.LDFLAGS}}" ./cmd/refyne-api

  api:test:
    desc: Run API tests
    dir: '{{.API_DIR}}'
    cmds:
      - go test -v ./...

  api:lint:
    desc: Lint API code
    dir: '{{.API_DIR}}'
    cmds:
      - golangci-lint run

  # Web tasks
  web:deps:
    desc: Install frontend dependencies
    dir: '{{.WEB_DIR}}'
    cmds:
      - npm install

  web:build:
    desc: Build frontend
    dir: '{{.WEB_DIR}}'
    cmds:
      - npm run build

  web:dev:
    desc: Run frontend in development mode
    dir: '{{.WEB_DIR}}'
    cmds:
      - npm run dev

  web:lint:
    desc: Lint frontend code
    dir: '{{.WEB_DIR}}'
    cmds:
      - npm run lint

  # Database tasks
  db:migrate:
    desc: Run database migrations (happens automatically on startup)
    dir: '{{.API_DIR}}'
    cmds:
      - echo "Migrations run automatically on API startup"

  # Combined tasks
  deps:
    desc: Install all dependencies
    cmds:
      - task: api:deps
      - task: web:deps

  build:
    desc: Build everything
    cmds:
      - task: api:build
      - task: web:build

  dev:
    desc: Start development servers (run in separate terminals)
    cmds:
      - echo "Run 'task api:dev' in one terminal"
      - echo "Run 'task web:dev' in another terminal"

  test:
    desc: Run all tests
    cmds:
      - task: api:test

  # Docker tasks
  docker:build:
    desc: Build Docker images
    cmds:
      - docker build -f deployments/docker/Dockerfile.api -t refyne-api:latest .
      - docker build -f deployments/docker/Dockerfile.web -t refyne-web:latest .

  docker:up:
    desc: Start Docker Compose
    cmds:
      - docker-compose -f deployments/docker/docker-compose.yml up -d

  docker:down:
    desc: Stop Docker Compose
    cmds:
      - docker-compose -f deployments/docker/docker-compose.yml down

  # Lint tasks
  lint:
    desc: Run linting across all components (api, web, demo)
    cmds:
      - task: api:lint
      - task: web:lint
      - task: demo:lint

  demo:lint:
    desc: Lint demo code
    dir: ./demo
    cmds:
      - npm run lint 2>/dev/null || echo "No lint script configured for demo"

  lint:fix:
    desc: Run linting with auto-fix across all components
    cmds:
      - task: api:lint:fix
      - task: web:lint:fix

  api:lint:fix:
    desc: Lint API code with auto-fix
    dir: '{{.API_DIR}}'
    cmds:
      - golangci-lint run --fix

  web:lint:fix:
    desc: Lint frontend code with auto-fix
    dir: '{{.WEB_DIR}}'
    cmds:
      - npm run lint -- --fix

  # Dependency tasks
  deps:update:
    desc: Update dependencies within compatible versions (safe)
    cmds:
      - task: api:deps:update
      - task: web:deps:update
      - task: demo:deps:update

  deps:upgrade:
    desc: Upgrade all dependencies to latest versions (may include breaking changes)
    cmds:
      - task: api:deps:upgrade
      - task: web:deps:upgrade
      - task: demo:deps:upgrade

  api:deps:update:
    desc: Update Go dependencies within compatible versions (safe)
    dir: '{{.API_DIR}}'
    cmds:
      - go get -u=patch ./...
      - go mod tidy

  api:deps:upgrade:
    desc: Upgrade Go dependencies to latest versions
    dir: '{{.API_DIR}}'
    cmds:
      - go get -u ./...
      - go mod tidy

  web:deps:update:
    desc: Update web dependencies within semver ranges (safe)
    dir: '{{.WEB_DIR}}'
    cmds:
      - npm update

  web:deps:upgrade:
    desc: Upgrade web dependencies to latest versions
    dir: '{{.WEB_DIR}}'
    cmds:
      - npx npm-check-updates -u
      - npm install

  demo:deps:update:
    desc: Update demo dependencies within semver ranges (safe)
    dir: ./demo
    cmds:
      - npm update

  demo:deps:upgrade:
    desc: Upgrade demo dependencies to latest versions
    dir: ./demo
    cmds:
      - npx npm-check-updates -u
      - npm install

  # Cleanup
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf web/.next/
      - rm -rf web/node_modules/
      - rm -rf demo/node_modules/
      - rm -rf demo/dist/

  # Version info
  version:
    desc: Show version information
    cmds:
      - echo "Version{{":"}} {{.VERSION}}"
      - echo "Commit{{":"}}  {{.COMMIT}}"
      - echo "Date{{":"}}    {{.DATE}}"
      - echo "Dirty{{":"}}   {{.DIRTY}}"
