// @ts-nocheck
import * as __fd_glob_47 from "../content/docs/api-reference/webhooks/index.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/api-reference/webhooks/id.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/api-reference/webhooks/deliveries.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/api-reference/sites/index.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/api-reference/sites/id.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/api-reference/schemas/index.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/api-reference/schemas/id.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/api-reference/jobs/index.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/api-reference/jobs/id.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/api-reference/jobs/id-results.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/api-reference/jobs/id-download.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/api-reference/llm/models-provider.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/api-reference/llm/keys.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/api-reference/llm/keys-id.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/api-reference/llm/chain.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/api-reference/keys/index.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/api-reference/keys/id.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/sdks/typescript.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/sdks/rust.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/sdks/python.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/sdks/index.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/sdks/go.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/sdks/curl.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/guides/webhooks.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/guides/schemas.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/guides/index.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/guides/extraction.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/guides/crawling.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/api-reference/usage.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/api-reference/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/api-reference/health.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/api-reference/extract.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/api-reference/crawl.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/api-reference/analyze.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/quickstart.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/plans-limits.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/authentication.mdx?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/api-reference/webhooks/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/api-reference/schemas/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/api-reference/sites/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/api-reference/llm/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/api-reference/keys/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/api-reference/jobs/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/sdks/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/api-reference/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "api-reference/meta.json": __fd_glob_1, "guides/meta.json": __fd_glob_2, "sdks/meta.json": __fd_glob_3, "api-reference/jobs/meta.json": __fd_glob_4, "api-reference/keys/meta.json": __fd_glob_5, "api-reference/llm/meta.json": __fd_glob_6, "api-reference/sites/meta.json": __fd_glob_7, "api-reference/schemas/meta.json": __fd_glob_8, "api-reference/webhooks/meta.json": __fd_glob_9, }, {"authentication.mdx": __fd_glob_10, "index.mdx": __fd_glob_11, "plans-limits.mdx": __fd_glob_12, "quickstart.mdx": __fd_glob_13, "api-reference/analyze.mdx": __fd_glob_14, "api-reference/crawl.mdx": __fd_glob_15, "api-reference/extract.mdx": __fd_glob_16, "api-reference/health.mdx": __fd_glob_17, "api-reference/index.mdx": __fd_glob_18, "api-reference/usage.mdx": __fd_glob_19, "guides/crawling.mdx": __fd_glob_20, "guides/extraction.mdx": __fd_glob_21, "guides/index.mdx": __fd_glob_22, "guides/schemas.mdx": __fd_glob_23, "guides/webhooks.mdx": __fd_glob_24, "sdks/curl.mdx": __fd_glob_25, "sdks/go.mdx": __fd_glob_26, "sdks/index.mdx": __fd_glob_27, "sdks/python.mdx": __fd_glob_28, "sdks/rust.mdx": __fd_glob_29, "sdks/typescript.mdx": __fd_glob_30, "api-reference/keys/id.mdx": __fd_glob_31, "api-reference/keys/index.mdx": __fd_glob_32, "api-reference/llm/chain.mdx": __fd_glob_33, "api-reference/llm/keys-id.mdx": __fd_glob_34, "api-reference/llm/keys.mdx": __fd_glob_35, "api-reference/llm/models-provider.mdx": __fd_glob_36, "api-reference/jobs/id-download.mdx": __fd_glob_37, "api-reference/jobs/id-results.mdx": __fd_glob_38, "api-reference/jobs/id.mdx": __fd_glob_39, "api-reference/jobs/index.mdx": __fd_glob_40, "api-reference/schemas/id.mdx": __fd_glob_41, "api-reference/schemas/index.mdx": __fd_glob_42, "api-reference/sites/id.mdx": __fd_glob_43, "api-reference/sites/index.mdx": __fd_glob_44, "api-reference/webhooks/deliveries.mdx": __fd_glob_45, "api-reference/webhooks/id.mdx": __fd_glob_46, "api-reference/webhooks/index.mdx": __fd_glob_47, });