# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  default: standard
  exclusions:
    # Don't lint test files with errcheck - it's common to ignore errors in tests
    rules:
      - path: "(.+)_test\\.go"
        linters:
          - errcheck
          - staticcheck
  settings:
    errcheck:
      # Ignore these functions where errors are commonly not checked
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*database/sql.Tx).Rollback
        - (*database/sql.Rows).Close
        - io.Copy
        - fmt.Fprintf
        - fmt.Printf
        - github.com/danielgtaylor/huma/v2.WriteErr
