package llm

import (
	_ "embed"
	"encoding/json"
	"log/slog"
)

// embeddedProviderModels contains the provider models JSON embedded at build time.
// This is generated by: go run ./cmd/generate_fallbacks
// The embedded config serves as a fallback when S3 is not available.
//
//go:embed provider_models_embed.json
var embeddedProviderModels []byte

// loadEmbeddedProviderModels parses the embedded JSON and returns provider models.
func loadEmbeddedProviderModels(logger *slog.Logger) map[string][]ModelInfo {
	if len(embeddedProviderModels) == 0 {
		if logger != nil {
			logger.Warn("no embedded provider models available")
		}
		return nil
	}

	var modelsFile ProviderModelsFile
	if err := json.Unmarshal(embeddedProviderModels, &modelsFile); err != nil {
		if logger != nil {
			logger.Error("failed to parse embedded provider models", "error", err)
		}
		return nil
	}

	// Convert to ModelInfo format
	providers := make(map[string][]ModelInfo)
	for providerName, providerData := range modelsFile.Providers {
		models := make([]ModelInfo, 0, len(providerData.Models))
		for _, m := range providerData.Models {
			models = append(models, ModelInfo{
				ID:                  m.ID,
				Name:                m.Name,
				Provider:            providerName,
				ContextWindow:       m.ContextWindow,
				MaxCompletionTokens: m.MaxOutput,
				Capabilities: ModelCapabilities{
					SupportsStructuredOutputs: m.Capabilities.SupportsStructuredOutputs,
					SupportsTools:             m.Capabilities.SupportsTools,
					SupportsStreaming:         m.Capabilities.SupportsStreaming,
					SupportsReasoning:         m.Capabilities.SupportsReasoning,
				},
				DefaultTemp:      GetDefaultSettings(providerName, m.ID).Temperature,
				DefaultMaxTokens: GetDefaultSettings(providerName, m.ID).MaxTokens,
			})
		}
		providers[providerName] = models
	}

	if logger != nil {
		totalModels := 0
		for _, models := range providers {
			totalModels += len(models)
		}
		logger.Info("loaded embedded provider models",
			"provider_count", len(providers),
			"total_models", totalModels,
		)
	}

	return providers
}
