// Code generated by go run ./internal/llm/generate_fallbacks. DO NOT EDIT.
// Generated: 2026-01-31T12:30:48Z
//
// To regenerate: go run ./internal/llm/generate_fallbacks -output internal/llm/model_fallbacks_gen.go

package llm

// StaticModelFallback represents a fallback model entry.
type StaticModelFallback struct {
	ID            string
	Name          string
	ContextWindow int
}


// HeliconeStaticFallbacks contains fallback models for Helicone.
// These are used when the dynamic API is unavailable.
var HeliconeStaticFallbacks = []StaticModelFallback{
	{ID: "chatgpt-4o-latest", Name: "OpenAI ChatGPT-4o", ContextWindow: 128000},
	{ID: "gpt-4o", Name: "OpenAI GPT-4o", ContextWindow: 128000},
	{ID: "gpt-4o-mini", Name: "OpenAI GPT-4o-mini", ContextWindow: 128000},
	{ID: "gpt-5", Name: "OpenAI GPT-5", ContextWindow: 400000},
	{ID: "gpt-5-2025-08-07", Name: "OpenAI GPT-5", ContextWindow: 400000},
	{ID: "gpt-5-chat-latest", Name: "OpenAI GPT-5 Chat Latest", ContextWindow: 128000},
	{ID: "gpt-5.1", Name: "OpenAI GPT-5.1", ContextWindow: 400000},
	{ID: "gpt-5.1-2025-11-13", Name: "OpenAI GPT-5.1", ContextWindow: 400000},
	{ID: "gpt-5.1-chat-latest", Name: "OpenAI GPT-5.1 Chat", ContextWindow: 128000},
	{ID: "gpt-5.1-codex", Name: "OpenAI: GPT-5.1 Codex", ContextWindow: 400000},
	{ID: "gpt-5.1-codex-mini", Name: "OpenAI: GPT-5.1 Codex Mini", ContextWindow: 400000},
	{ID: "gpt-5.2", Name: "OpenAI GPT-5.2", ContextWindow: 400000},
	{ID: "gpt-5.2-chat-latest", Name: "OpenAI GPT-5.2 Chat", ContextWindow: 128000},
	{ID: "gpt-5.2-pro", Name: "OpenAI: GPT-5.2 Pro", ContextWindow: 400000},
	{ID: "o3", Name: "OpenAI o3", ContextWindow: 200000},
}

// OpenrouterStaticFallbacks contains fallback models for OpenRouter.
// These are used when the dynamic API is unavailable.
var OpenrouterStaticFallbacks = []StaticModelFallback{
	{ID: "anthropic/claude-sonnet-4", Name: "Anthropic: Claude Sonnet 4", ContextWindow: 1000000},
	{ID: "anthropic/claude-sonnet-4.5", Name: "Anthropic: Claude Sonnet 4.5", ContextWindow: 1000000},
	{ID: "anthropic/claude-opus-4", Name: "Anthropic: Claude Opus 4", ContextWindow: 200000},
	{ID: "openai/gpt-4o", Name: "OpenAI: GPT-4o", ContextWindow: 128000},
	{ID: "openai/gpt-4o-2024-05-13", Name: "OpenAI: GPT-4o (2024-05-13)", ContextWindow: 128000},
	{ID: "openai/gpt-4o-2024-08-06", Name: "OpenAI: GPT-4o (2024-08-06)", ContextWindow: 128000},
	{ID: "google/gemini-2.5-flash", Name: "Google: Gemini 2.5 Flash", ContextWindow: 1048576},
	{ID: "google/gemini-2.5-flash-image", Name: "Google: Gemini 2.5 Flash Image (Nano Banana)", ContextWindow: 32768},
	{ID: "google/gemini-2.5-flash-lite", Name: "Google: Gemini 2.5 Flash Lite", ContextWindow: 1048576},
	{ID: "google/gemini-2.5-flash-lite-preview-09-2025", Name: "Google: Gemini 2.5 Flash Lite Preview 09-2025", ContextWindow: 1048576},
	{ID: "google/gemini-2.5-flash-preview-09-2025", Name: "Google: Gemini 2.5 Flash Preview 09-2025", ContextWindow: 1048576},
	{ID: "google/gemini-2.5-pro", Name: "Google: Gemini 2.5 Pro", ContextWindow: 1048576},
	{ID: "google/gemini-2.5-pro-preview", Name: "Google: Gemini 2.5 Pro Preview 06-05", ContextWindow: 1048576},
	{ID: "google/gemini-2.5-pro-preview-05-06", Name: "Google: Gemini 2.5 Pro Preview 05-06", ContextWindow: 1048576},
	{ID: "google/gemini-2.0-flash-001", Name: "Google: Gemini 2.0 Flash", ContextWindow: 1048576},
}

// AnthropicStaticFallbacks contains fallback models for Anthropic.
// These are used when the dynamic API is unavailable.
var AnthropicStaticFallbacks = []StaticModelFallback{
	{ID: "claude-opus-4-20250514", Name: "Claude Opus 4", ContextWindow: 200000},
	{ID: "claude-sonnet-4-5-20250514", Name: "Claude Sonnet 4.5", ContextWindow: 200000},
	{ID: "claude-sonnet-4-20250514", Name: "Claude Sonnet 4", ContextWindow: 200000},
	{ID: "claude-3-7-sonnet-20250219", Name: "Claude 3.7 Sonnet", ContextWindow: 200000},
	{ID: "claude-3-5-sonnet-20241022", Name: "Claude 3.5 Sonnet v2", ContextWindow: 200000},
	{ID: "claude-3-5-haiku-20241022", Name: "Claude 3.5 Haiku", ContextWindow: 200000},
	{ID: "claude-3-opus-20240229", Name: "Claude 3 Opus", ContextWindow: 200000},
	{ID: "claude-3-sonnet-20240229", Name: "Claude 3 Sonnet", ContextWindow: 200000},
	{ID: "claude-3-haiku-20240307", Name: "Claude 3 Haiku", ContextWindow: 200000},
}

// OpenaiStaticFallbacks contains fallback models for OpenAI.
// These are used when the dynamic API is unavailable.
var OpenaiStaticFallbacks = []StaticModelFallback{
	{ID: "gpt-4o", Name: "GPT-4o", ContextWindow: 128000},
	{ID: "gpt-4o-mini", Name: "GPT-4o Mini", ContextWindow: 128000},
	{ID: "gpt-4-turbo", Name: "GPT-4 Turbo", ContextWindow: 128000},
	{ID: "gpt-4", Name: "GPT-4", ContextWindow: 8192},
	{ID: "gpt-3.5-turbo", Name: "GPT-3.5 Turbo", ContextWindow: 16385},
	{ID: "o1", Name: "o1", ContextWindow: 200000},
	{ID: "o1-mini", Name: "o1 Mini", ContextWindow: 128000},
	{ID: "o3-mini", Name: "o3 Mini", ContextWindow: 200000},
}

// OllamaStaticFallbacks contains fallback models for Ollama.
// These are used when the dynamic API is unavailable.
var OllamaStaticFallbacks = []StaticModelFallback{
	{ID: "llama3.2", Name: "Llama 3.2", ContextWindow: 128000},
	{ID: "llama3.1", Name: "Llama 3.1", ContextWindow: 128000},
	{ID: "mistral", Name: "Mistral", ContextWindow: 32768},
	{ID: "gemma2", Name: "Gemma 2", ContextWindow: 8192},
	{ID: "qwen2.5", Name: "Qwen 2.5", ContextWindow: 32768},
	{ID: "deepseek-coder-v2", Name: "DeepSeek Coder V2", ContextWindow: 128000},
	{ID: "phi3", Name: "Phi-3", ContextWindow: 128000},
	{ID: "codellama", Name: "Code Llama", ContextWindow: 16384},
}


// GetStaticFallbacks returns the static fallback models for a provider.
func GetStaticFallbacks(provider string) []StaticModelFallback {
	switch provider {
	case "helicone":
		return HeliconeStaticFallbacks
	case "openrouter":
		return OpenrouterStaticFallbacks
	case "anthropic":
		return AnthropicStaticFallbacks
	case "openai":
		return OpenaiStaticFallbacks
	case "ollama":
		return OllamaStaticFallbacks
	default:
		return nil
	}
}
